import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// Helper to load images safely (like QR code)
const loadImage = (url) => {
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => resolve(img);
    img.onerror = () => resolve(null);
    img.src = url;
  });
};

/**
 * Generates a professional medical diagnostic PDF report using jsPDF + AutoTable
 * @param {Object} fullReport Consolidated full EMR report object from backend
 * @param {Object} user Logged in user profile context
 */
export const generatePdfReport = async (fullReport, user) => {
  if (!fullReport || !fullReport.patient_info) {
    throw new Error('Incomplete EMR data. Cannot generate PDF report.');
  }

  const {
    id: reportId,
    assessment_date: dateGenerated = 'Not Provided',
    assessment_time: timeGenerated = 'Not Provided',
    patient_info: pInfo = {},
    lifestyle = {},
    medical_history: medHistory = {},
    symptoms_details: symInfo = {},
    vitals = {},
    lab_values: labs = {},
    prediction_results: pred = {},
    ai_analysis: ai = {}
  } = fullReport;

  const patientName = pInfo.patient_name || 'Anonymous Patient';
  const filename = `HealthGuard_EMR_Report_${patientName.replace(/\s+/g, '_')}_${reportId}.pdf`;

  // Initialize jsPDF A4 format
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth(); // ~210mm
  const pageHeight = doc.internal.pageSize.getHeight(); // ~297mm
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2); // ~180mm

  // Colors
  const primaryColor = [30, 41, 59]; // slate-800
  const primaryAccent = [13, 148, 136]; // teal-600
  const textDark = [51, 65, 85]; // slate-700
  const borderColor = [226, 232, 240]; // slate-200

  // ----------------------------------------------------
  // Helper to draw headers & footers
  // ----------------------------------------------------
  const drawPageDecorations = (docNum, totalPages) => {
    doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
    doc.setLineWidth(0.3);

    // Header (every page after Page 1)
    if (docNum > 1) {
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184); // slate-400
      doc.text('HealthGuard AI  |  Hospital Electronic Medical Record (EMR)', margin, 10);
      doc.text(`Report ID: ${reportId}`, pageWidth - margin, 10, { align: 'right' });
      doc.line(margin, 12, pageWidth - margin, 12);
    }

    // Footer (all pages)
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text('CONFIDENTIAL EMR RECORD  -  Generated by HealthGuard AI Platform', margin, pageHeight - 10);
    doc.text(`Page ${docNum} of ${totalPages}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
  };

  // ----------------------------------------------------
  // COVER PAGE (PAGE 1)
  // ----------------------------------------------------
  
  // 1. Clinical Header Band
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, pageWidth, 55, 'F');
  
  // Brand Logo (styled cross + text)
  doc.setFillColor(primaryAccent[0], primaryAccent[1], primaryAccent[2]);
  doc.rect(margin, 15, 8, 24, 'F');
  doc.rect(margin - 8, 23, 24, 8, 'F');

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text('HealthGuard AI', margin + 20, 27);
  
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(186, 230, 253); // light sky-200
  doc.text('HOSPITAL ELECTRONIC MEDICAL RECORD (EMR) SYSTEM', margin + 20, 34);

  // 2. Report Main Title
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('CLINICAL HEALTH REPORT', margin, 75);
  
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(primaryAccent[0], primaryAccent[1], primaryAccent[2]);
  doc.text('SECURED INTEGRATED DATABASE FILE', margin, 82);

  // 3. Patient Details Box
  doc.setFontSize(10);
  doc.setFont('Helvetica', 'bold');
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('PATIENT DEMOGRAPHIC PROFILE', margin, 98);

  const patientProfileData = [
    ['Patient Name:', patientName, 'Date Generated:', `${dateGenerated} ${timeGenerated}`],
    ['Age / DOB:', `${pInfo.age} Yrs / ${pInfo.dob}`, 'Report ID:', reportId],
    ['Gender:', pInfo.gender, 'Height / Weight:', `${pInfo.height} cm / ${pInfo.weight} kg`],
    ['BMI:', `${pInfo.bmi}`, 'Relationship:', pInfo.relationship],
    ['Phone:', pInfo.phone, 'Emergency Phone:', pInfo.emergency_contact],
    ['Assessment Ref:', fullReport.assessment_id, '-', '-']
  ];

  autoTable(doc, {
    startY: 102,
    body: patientProfileData,
    theme: 'grid',
    styles: {
      fontSize: 9,
      cellPadding: 3,
      textColor: textDark,
      lineColor: borderColor
    },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [248, 250, 252], width: 35 },
      1: { width: 55 },
      2: { fontStyle: 'bold', fillColor: [248, 250, 252], width: 35 },
      3: { width: 55 }
    }
  });

  // 4. Summary Executive Badges
  const statsY = doc.lastAutoTable.finalY + 12;
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('CLINICAL EVALUATION METRICS', margin, statsY);

  const healthScore = pred.overall_health_score || 0;
  const overallRisk = pred.overall_risk || 'Low';

  // Draw Score Box
  doc.setFillColor(248, 250, 252);
  doc.rect(margin, statsY + 4, 85, 30, 'F');
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(textDark[0], textDark[1], textDark[2]);
  doc.text('HEALTH INDEX SCORE', margin + 6, statsY + 12);
  doc.setFontSize(22);
  doc.setTextColor(primaryAccent[0], primaryAccent[1], primaryAccent[2]);
  doc.text(`${healthScore}/100`, margin + 6, statsY + 24);

  // Draw Risk Box
  doc.setFillColor(overallRisk === 'High' ? 254 : 248, overallRisk === 'High' ? 242 : 250, overallRisk === 'High' ? 242 : 252);
  doc.rect(margin + 95, statsY + 4, 85, 30, 'F');
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(textDark[0], textDark[1], textDark[2]);
  doc.text('DIAGNOSTIC RISK STATUS', margin + 101, statsY + 12);
  doc.setFontSize(18);
  doc.setTextColor(overallRisk === 'High' ? 220 : overallRisk === 'Moderate' ? 217 : 13, overallRisk === 'High' ? 38 : overallRisk === 'Moderate' ? 119 : 148, overallRisk === 'High' ? 38 : overallRisk === 'Moderate' ? 6 : 136);
  doc.text(overallRisk.toUpperCase(), margin + 101, statsY + 24);

  // 5. Active Symptoms
  const symptomsY = statsY + 44;
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('ACTIVE SYMPTOMS & CHIEF COMPLAINTS', margin, symptomsY);

  autoTable(doc, {
    startY: symptomsY + 4,
    body: [
      ['Description:', symInfo.symptom_description],
      ['Severity Index:', symInfo.severity || 'Not Provided'],
      ['Duration:', symInfo.duration || 'Not Provided']
    ],
    theme: 'grid',
    styles: {
      fontSize: 9,
      cellPadding: 3,
      textColor: textDark,
      lineColor: borderColor
    },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [248, 250, 252], width: 35 },
      1: { width: 145 }
    }
  });

  drawPageDecorations(1, 3);

  // ----------------------------------------------------
  // PAGE 2: VITALS, LAB VALUES, LIFESTYLE, HISTORY
  // ----------------------------------------------------
  doc.addPage();
  
  // 1. Vitals Signs Section
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('1. CLINICAL VITAL SIGNS', margin, 20);

  const vitalsData = [
    ['Blood Pressure:', vitals.blood_pressure, 'Heart Rate:', vitals.heart_rate],
    ['Body Mass Index:', vitals.bmi, '-', '-']
  ];

  autoTable(doc, {
    startY: 24,
    body: vitalsData,
    theme: 'grid',
    styles: { fontSize: 8.5, cellPadding: 2.5, lineColor: borderColor },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [248, 250, 252], width: 35 },
      1: { width: 55 },
      2: { fontStyle: 'bold', fillColor: [248, 250, 252], width: 35 },
      3: { width: 55 }
    }
  });

  // 2. Lab Values Section
  const labsY = doc.lastAutoTable.finalY + 8;
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('2. LABORATORY INVESTIGATIONS MATRIX', margin, labsY);

  const labsData = [
    ['Blood Sugar:', labs.blood_sugar, 'Cholesterol Total:', labs.cholesterol]
  ];

  autoTable(doc, {
    startY: labsY + 4,
    body: labsData,
    theme: 'grid',
    styles: { fontSize: 8.5, cellPadding: 2.5, lineColor: borderColor },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [248, 250, 252], width: 35 },
      1: { width: 55 },
      2: { fontStyle: 'bold', fillColor: [248, 250, 252], width: 35 },
      3: { width: 55 }
    }
  });

  // 3. Lifestyle & History splits
  const lifestyleY = doc.lastAutoTable.finalY + 8;
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('3. LIFESTYLE HABITS', margin, lifestyleY);

  const lifestyleHistoryData = [
    ['Exercise habit:', lifestyle.exercise, 'Tobacco / Smoking:', lifestyle.smoking],
    ['Alcohol Intake:', lifestyle.alcohol, '-', '-']
  ];

  autoTable(doc, {
    startY: lifestyleY + 4,
    body: lifestyleHistoryData,
    theme: 'grid',
    styles: { fontSize: 8.5, cellPadding: 2.5, lineColor: borderColor },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [248, 250, 252], width: 35 },
      1: { width: 55 },
      2: { fontStyle: 'bold', fillColor: [248, 250, 252], width: 35 },
      3: { width: 55 }
    }
  });

  drawPageDecorations(2, 3);

  // ----------------------------------------------------
  // PAGE 3: ML PREDICTION & GEMINI ASSISTANCE
  // ----------------------------------------------------
  doc.addPage();

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('4. MULTI-ORGAN PREDICTIVE THREAT ASSESSMENT', margin, 20);

  const organRisks = pred.disease_risks || {};
  const organRisksData = [
    ['Cardiovascular Heart Risk:', `${organRisks.cardioRisk}%`, 'Kidney Filtration Risk:', `${organRisks.kidneyRisk}%`],
    ['Endocrine Diabetes Risk:', `${organRisks.diabetesRisk}%`, 'Hepatocyte Liver Risk:', `${organRisks.liverRisk}%`],
    ['Neurological Stroke Risk:', `${organRisks.strokeRisk}%`, 'Hypertension Strain Risk:', `${organRisks.hypertensionRisk}%`],
    ['Obesity Index Risk:', `${organRisks.obesityRisk}%`, 'Confidence Index:', `${pred.prediction_confidence}%`]
  ];

  autoTable(doc, {
    startY: 24,
    body: organRisksData,
    theme: 'grid',
    styles: { fontSize: 8.5, cellPadding: 2.5, lineColor: borderColor },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [248, 250, 252], width: 35 },
      1: { width: 55 },
      2: { fontStyle: 'bold', fillColor: [248, 250, 252], width: 35 },
      3: { width: 55 }
    }
  });

  // Physician Summary
  const summaryY = doc.lastAutoTable.finalY + 8;
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('5. GENERATIVE PHYSICIAN CLINICAL REVIEW SUMMARY', margin, summaryY);

  const textLines = doc.splitTextToSize(ai.gemini_summary, contentWidth);
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(textDark[0], textDark[1], textDark[2]);
  doc.rect(margin, summaryY + 4, contentWidth, textLines.length * 4.2 + 8, 'F');
  doc.text(textLines, margin + 4, summaryY + 10);

  // Recommendations Grid
  const recsY = summaryY + 4 + textLines.length * 4.2 + 12;
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('6. GROUPED PHYSICIAN CARE RECOMMENDATIONS', margin, recsY);

  const formatList = (arr) => {
    if (!arr || arr[0] === 'Not Provided') return 'None recorded.';
    if (Array.isArray(arr)) {
      if (arr.length === 0) return 'None recorded.';
      return arr.map(i => `• ${i}`).join('\n');
    }
    if (typeof arr === 'string' && arr.trim()) {
      return `• ${arr}`;
    }
    if (typeof arr === 'object') {
      const vals = Object.values(arr).filter(Boolean);
      if (vals.length > 0) {
        return vals.map(v => `• ${typeof v === 'string' ? v : JSON.stringify(v)}`).join('\n');
      }
    }
    return 'None recorded.';
  };

  const recsData = [
    ['Nutrition Care Plan:', formatList(ai.gemini_recommendations?.diet), 'Daily Exercises:', formatList(ai.gemini_recommendations?.exercise)],
    ['Medications Protocol:', formatList(ai.gemini_recommendations?.medication), 'Daily Hydration Plan:', formatList(ai.gemini_recommendations?.hydration)],
    ['Sleep Quality Advice:', formatList(ai.gemini_recommendations?.sleep), 'Stress Reduction:', formatList(ai.gemini_recommendations?.stress)],
    ['Preventive Precaution:', formatList(ai.gemini_recommendations?.preventive_care), 'Lifestyle Modifications:', formatList(ai.gemini_recommendations?.lifestyle)],
    ['Emergency Plan:', formatList(ai.gemini_recommendations?.medical_followup), '-', '-']
  ];

  autoTable(doc, {
    startY: recsY + 4,
    body: recsData,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2, valign: 'top', lineColor: borderColor },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [248, 250, 252], width: 35 },
      1: { width: 55 },
      2: { fontStyle: 'bold', fillColor: [248, 250, 252], width: 35 },
      3: { width: 55 }
    }
  });

  drawPageDecorations(3, 3);

  // Save / Download trigger
  doc.save(filename);
};
